sudo: required
dist: xenial
language: python
python:
  - '2.7'
install:
 - test -z "$TESTS_ONLY" || pip install -r ci/requirements.txt
 - test -n "$TESTS_ONLY" || git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script:
 - test -z "$TESTS_ONLY" || python -m unittest discover -v imgconverter -p test.py
 - test -n "$TESTS_ONLY" || GIT_URL_builder_rpm=https://github.com/marmarek/qubes-builder-rpm BRANCH_builder_rpm=travis NO_CHECK=1 ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc27 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc28 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc29 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 USE_DIST_BUILD_TOOLS=1
 - DISTS_VM=jessie USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 USE_DIST_BUILD_TOOLS=1
 - DISTS_VM=buster USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 USE_DIST_BUILD_TOOLS=1
 - DISTS_VM=centos7 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1

jobs:
  include:
   - env: TESTS_ONLY=1
     python: 2.7
   - env: TESTS_ONLY=1
     python: 3.4
   - env: TESTS_ONLY=1
     python: 3.5
   - stage: deploy
     python: 3.5
     env: DIST_DOM0=fc25 TESTS_ONLY=
     script: ~/qubes-builder/scripts/travis-deploy

# don't build tags which are meant for code signing only
branches:
  except:
    - /.*_.*/

